### ISSUE TITLE
Log does not show anything

### ISSUE THREAD

**Issue by fleshgolem** [ad-on-is/resticity#2]
I setup the app in a docker container, successfully added a repository and a backup, ran the backup, setup pruning rules and pruned the repo. Still there is no text at all on the log page

![image](https://github.com/ad-on-is/resticity/assets/657606/d7861de8-bfc1-4886-8d10-1f13bcc2babe)

I am not sure what is supposed to be here, but it would be nice to have a bit more detailed output from restic somewhere, instead of just the green checkmark from the schedules

**Comment by fleshgolem** [comment]
Upon further inspection, I do get the following error in the browser log, when opening the page:
```
TypeError: (intermediate value)().settings is undefined
    NuxtJS 80
entry.DpM32KHl.js:13:584
```

**Comment by ad-on-is** [comment]
Yeah, the log page is still in progress 😅 you can see them in the container.

**Comment by ad-on-is** [comment]
> Upon further inspection, I do get the following error in the browser log, when opening the page:
> 
> ```
> TypeError: (intermediate value)().settings is undefined
>     NuxtJS 80
> entry.DpM32KHl.js:13:584
> ```

This is happens when you reload the page if you're not on the dashboard, need to rework that

**Comment by ad-on-is** [comment]
Logs are implemented in the newest release. Still need some rework tho.
