### ISSUE TITLE
Use a separate secrets file to store passwords and api keys

### ISSUE THREAD

**Issue by jeremy-lockwood** [ad-on-is/resticity#4]
I use a lot of gitops, and would love to add the `config.json` file to my repo for easy backup/restore. Unfortunately, `config.json` currently contains passwords and api keys in plain text. It goes without saying that it would be a disaster to commit the file to git.

There are any number of ways to improve this issue, but the simplest would probably be to just have a separate secrets file kept in the same directory as `config.jason`. The secrets file could be added to `.gitignore`, and `config.json` could be committed to git without issue.

**Comment by ad-on-is** [comment]
Yeah, I thought about the secrets file, but then came to the conclusion, that the `config.json` should be treated the same way as a secrets file, stored secretly and carefully.

But for people who manage their dotfiles, this would of course make sense.

**Comment by ad-on-is** [comment]
> I appreciate you taking the time to explain your thought process on this! Thank you!
> 
> This project is really just crazy awesome, and I'm really excited to be able to use it. I'll be keeping an eye out for if you decide to release an update that lets me keep my config on git. Keep up the awesome work!

I'll get back to this one for sure, once I've finished the CI/CD and release process, with other minor improvements.

**Comment by ad-on-is** [comment]
Secrets file is added now.
