### ISSUE TITLE
JSON file creation

### ISSUE THREAD

**Issue by flamingm0e** [ad-on-is/resticity#5]
Finally a good looking Restic GUI!

Thank you.

Installed on Arch, but when attempting to connect to my existing repository, it would crash out after connection in repositories

Looking at the logs, it appears it was trying to save to `~/.config/resticity/config.json` which didn't get created on install or first run.  Creating the directory and touching the json file fixed the issue.

**Comment by ad-on-is** [comment]
Will look into that, but the file should be created on first run.

**Comment by ad-on-is** [comment]
Fixed in newest release
