### ISSUE TITLE
Segmentation violation

### ISSUE THREAD

**Issue by MDaniel592** [ad-on-is/resticity#8]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x816a55]

goroutine 6 [running]:
github.com/ad-on-is/resticity/internal.runHub()
        /build/internal/server.go:64 +0x335
created by github.com/ad-on-is/resticity/internal.RunServer in goroutine 1
        /build/internal/server.go:208 +0x1b0
        
I do not really know how, but sometimes the GUI/server fails. I am running the docker image. I must restart the container.

**Comment by ad-on-is** [comment]
Thx... I found the possible cause... it's hopefully fixed in 1.36.0
